TINY_PROFILE = FALSE
DEBUG   		 = TRUE
DIM     		 = 3
COMP 			 = gcc
USE_CUDA 		 = FALSE
USE_MPI 		 = FALSE
USE_OMP 		 = FALSE

USE_GPIBM		 = FALSE

include ./Make.package
include $(AMREX_HOME)/../../src/Make.CNS
