TINY_PROFILE = FALSE
DEBUG   		 = FALSE
PRECISION    = DOUBLE # DOUBLE or FLOAT
DIM     		 = 3
COMP 			 = gcc
USE_CUDA 		 = TRUE
USE_MPI 		 = FALSE
USE_OMP 		 = FALSE

USE_GPIBM		 = FALSE

include ./Make.package
include $(AMREX_HOME)/../../src/Make.CNS
